### ISSUE TITLE
Certify request: exception occurred

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ESV-Server#11]
I sent the following data to the /certify endpoint:

```
[
  {
    "esvVersion":"1.0"
  },
  {
    "itar":false,
    "limitEntropyAssessmentToSingleModule":false,
    "moduleId":12827,
    "vendorId":11176,
    "supportingDocumentation":[
      {
        "sdId":270031,
        "accessToken":"access token received for SD"
      }
    ],
    "entropyAssessments":[
      {
        "eaId":20154,
        "oeId":31916,
        "accessToken":"token obtained for ea"
      }
    ]
  }
]
```

The server returned:

```
[
  {
    "esvVersion": "1.0"
  },
  {
    "status": "error",
    "errors": {
      "errorList": [
        "TestPredicates: vendorId An Exception occured.",
        "TestPredicates: moduleId An Exception occured."
      ],
      "entropyAssessmentsReferences": {
        "elementList": [
          {
            "location": "indexPosition:1",
            "messageList": [
              "TestPredicates: oeId An Exception occured.",
              "TestPredicates: oeId An Exception occured."
            ]
          }
        ]
      }
    },
    "information": {
      "messageList": [
        "TestPredicates: vendorId An Exception occured.",
        "TestPredicates: moduleId An Exception occured."
      ],
      "entropyAssessmentsReferences": {
        "elementList": [
          {
            "location": "indexPosition:1",
            "messageList": [
              "TestPredicates: oeId An Exception occured."
            ]
          }
        ]
      }
    }
  }
]
```

Note: may I ask for a clarification on the relationship of the access token that should be used for the authorization bearer? At the moment, I use the ea-access token as authorization bearer.

**Comment by celic** [comment]
You can use any valid access token for the header. I am seeing this same error now, we are diagnosing the problem.

**Comment by smuellerDD** [comment]
Confirmed, working.

But what is the next step? I would have expected that I get a kind of request ID like for ACVP where I can ask NIST to give me a certificate?

**Comment by celic** [comment]
Next step is on the NIST side. Data gets bundled and sent to Resolve for a
manual review. Labs are updated on progress using encrypted email via the
normal module review process.

**Comment by smuellerDD** [comment]
Am Freitag, dem 10.09.2021 um 05:41 -0700 schrieb Chris Celi:
> Next step is on the NIST side. Data gets bundled and sent to Resolve for a
> manual review. Labs are updated on progress using encrypted email via the
> normal module review process.

Ok, but isn't there a kind of ID that allows us to refer to the open request?
What happens if a lab has 10 parallel requests outstanding. How can we
identify a particular outstanding validation?

Thanks
Stephan

**Comment by celic** [comment]
Soon we will add in a TID (or similar) for a lab to track the entry.

**Comment by celic** [comment]
Fixed in the latest release to Demo. Added an "EID" field for tracking a submission through the review process. Will update documentation.
