### ISSUE TITLE
Webpage bug: one-bit sample, alphabet size of 2

### ISSUE THREAD

**Issue by locksmithone** [usnistgov/ESV-Server#14]
Webpage, first page. While attempting to register the information for the entropy source, it is asked the sample length and the alphabet size.

For one-bit samples, the alphabet size is 2. Yet, this configuration is refused by the server: "alphabet size invalid."

**Comment by celic** [comment]
Yup, clearly a bug. Thanks.

**Comment by celic** [comment]
This should be fixed, please confirm and close when you can.
