### ISSUE TITLE
Server does not associate uploaded data with test session

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ESV-Server#15]
My client uploaded 3 data files with the following success indicators:

/esv/v1/entropyAssessments/121/dataFiles/430
```
  {
    "uploadType": "UploadDataFile",
    "status": "success",
    "dataLengthBytes": 1000000
  }
```

/esv/v1/entropyAssessments/121/dataFiles/431:
```
  {
    "uploadType": "UploadDataFile",
    "status": "success",
    "dataLengthBytes": 1000000
  }
```
/esv/v1/supportingDocumentation:
```
  {
    "sdId": 20049,
    "uploadType": "UploadSupportingDocumentation",
    "status": "success",
    "dataLengthBytes": 13188388,
    "accessToken": "xxx"
  }
```

During certify the client references them as:

```
"entropyId":"JENT",
"moduleId":12827,
"vendorId":11176,
"supportingDocumentation":[{
"sdId":20049,
"accessToken":"xxxx"

...
```

The server answers:

```
{
            "location": "indexPosition:1, EntropyAssessmentId: 121",
            "messageList": [
              "RawNoiseBits DataFile may not be available yet or an unexpected exception. Check server log for details.",
              "RestartBits DataFile may not be available yet or an unexpected exception. Check server log for details.",
              "ConditionedBits DataFile may not be available yet or an unexpected exception. Check server log for details."
            ]
          }
```

Note, the ES uses a vetted conditioning component and the server rightfully only requests the raw noise data which is fulfilled with the submissions above:

```
  {
    "url": "/esvp/v1/entropyAssessments/121",
    "createdOn": "2022-03-28T05:18:35.9788087-04:00",
    "expiresOn": "2022-03-28T05:18:35.9788096-04:00",
    "dataFileUrls": [
      {
        "rawNoiseBits": "/esvp/v1/entropyAssessments/121/dataFiles/430"
      },
      {
        "restartTestBits": "/esvp/v1/entropyAssessments/121/dataFiles/431"
      }
    ]
```

**Comment by celic** [comment]
Correct, we should not be expecting a "completed datafile" for vetted conditioning components. That appears to be the bug here... assuming there are no server-side errors in those test runs. If you Certify before the tests complete, we will throw an error. There is no "intelligent" queueing of the actions here.

**Comment by smuellerDD** [comment]
Am Montag, 28. März 2022, 19:42:11 CEST schrieb Chris Celi:

Hi Chris,

> Correct, we should not be expecting a "completed datafile" for vetted
> conditioning components. That appears to be the bug here... assuming there
> are no server-side errors in those test runs. If you Certify before the
> tests complete, we will throw an error. There is no "intelligent" queueing
> of the actions here.

After re-starting the certify process this morning with the testID 121 
submitted yesterday (and refreshing all auth tokens), I still get the same 
error as yesterday. This makes me believe that some issue is lingering in the 
ESV server.

In any case, if there is no proper queueing mechanism (yet?), I would like to 
ask you to return an unambiguous error indicator that identifies that the 
number crunching is ongoing. In case there is, please disregard my comment.

Thanks.

Ciao
Stephan

**Comment by celic** [comment]
There is. Run a GET on the data file url.

**Comment by smuellerDD** [comment]
Am Dienstag, 29. März 2022, 14:56:25 CEST schrieb Chris Celi:

Hi Chris,

> There is. Run a GET on the data file url.

Hm, what additional information do you think I get from that:

```
  {
    "id": 433,
    "status": "Uploaded",
    "sha256": 
"3bf95db5864e17b66ac7629aa03a05d11c3ad057a0f0a341e32e9cb40872b1f4"
  }
```

Thanks
Stephan
Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Dienstag, 29. März 2022, 14:56:25 CEST schrieb Chris Celi:

Hi Chris,

> There is. Run a GET on the data file url.

I see now, you seem to have updated the certify response:

```
            "location": "indexPosition:1, EntropyAssessmentId: 122",
            "messageList": [
              "RawNoiseBits: dataFileId 432: Results are not yet available.",
              "RawNoiseBits: dataFileId 432: Status is not Run Successful.",
              "RestartBits: dataFileId 433: Results are not yet available.",
              "RestartBits: dataFileId 433: Status is not Run Successful."
            ]
```

That is certainly helpful

Ciao
Stephan

**Comment by celic** [comment]
Great. I'll look into the runs failing.

Chris
