### ISSUE TITLE
Data uploaded but server does not find it

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ESV-Server#16]
eaID 292

The raw noise data and restart data is uploaded:

data file 829 (raw noise) and 830 (restart) both receive

```
[
  {
    "esvVersion": "1.0"
  },
  {
    "uploadType": "UploadDataFile",
    "status": "success",
    "dataLengthBytes": 1000000
  }
]
```

When POSTing /certify, I get:

```
[
  {
    "esvVersion": "1.0"
  },
  {
    "status": "error",
    "errors": {
      "entropyAssessmentsReferences": {
        "elementList": [
          {
            "location": "indexPosition:1, EntropyAssessmentId: 292",
            "messageList": [
              "RawNoiseBits DataFile may not be available yet or an unexpected exception. Check server log for details.",
              "RestartBits DataFile may not be available yet or an unexpected exception. Check server log for details.",
              "ConditionedBits DataFile may not be available yet or an unexpected exception. Check server log for details."
            ]
          }
        ]
      }
    },
    "information": {
      "messageList": [
        "moduleId name is Jitter RNG (Generic C)."
      ],
      "entropyAssessmentsReferences": {
        "elementList": [
          {
            "location": "indexPosition:1, EntropyAssessmentId: 292",
            "messageList": [
              "oeId name is Fedora 32 on Intel Broadwell i7."
            ]
          }
        ]
      }
    }
  }
]
```

Note, I do have a vetted conditioning component, so no conditioned bits were sent.

Note2: This very setup with the very same data was successfully processed (e.g. eaID 122).

**Comment by celic** [comment]
How soon are you trying to certify after sending the data files? Are you confirming that the data files have completed their testing?

**Comment by smuellerDD** [comment]
Am Montag, 23. Mai 2022, 18:08:55 CEST schrieb Chris Celi:

Hi Chris,

> How soon are you trying to certify after sending the data files? Are you
> confirming that the data files have completed their testing?

Sorry for the delay. I try to certify right after submitting the data. If you 
say, I have to wait, shouldn't there be a "retry:30" answer by the server?

Ciao
Stephan

**Comment by celic** [comment]
There is a wait status if you perform a GET on the data file url you just
uploaded to. You can only certify after that GET returns a success status.

The certify will tell you the files haven't finished yet as-is.

**Comment by celic** [comment]
I am going to close this issue unless you have additional comments. The question was answered.
