### ISSUE TITLE
Entropy Source Registration File Issues

### ISSUE THREAD

**Issue by tarcode2004** [usnistgov/ESV-Server#18]
The EntropySourceValidationProtocol.md file has an example entropy assessments JSON file with a typo and a missing required field. The example file has a comma where there should be no comma. See image attached. The "itar" field seems necessary for the application to proceed, however, is not included in the example JSON file. 

When one of the fields in the Entropy Assessment JSON is missing the error provided has information pointing to the missing field. However, when "conditioningComponent" is missing the server returns a 500 response, internal service error, without context. 

<img width="628" alt="ESV-Err1" src="https://user-images.githubusercontent.com/66574422/174092358-7349c01f-e7f4-4957-936e-ae444acdd80e.png">

**Comment by celic** [comment]
Thanks. I can fix the documentation issues now. I'll log the 500 for a dev to tackle.

**Comment by celic** [comment]
It appears that if the `conditioningComponents` array is included but empty, everything proceeds as expected. If the array is excluded entirely, then you get the 500 error. Ideally these two cases should lead to identical behavior from the server, so we'll look at that.

**Comment by celic** [comment]
This is fixed on Demo.
