### ISSUE TITLE
Unable to upload raw noise bits (probably user error)

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ESV-Server#2]
Having just received credentials, I thought I'd start poking around as ESVP.  I successfully registered an entropy source.  I then tried to upload the raw noise bits file but it doesn't seem to be working for me.  I am using curl to test it out in order to keep things simple.

My curl command is as follows:

```
curl -F datafile=@./<SOMEFILE> \
    -H "Content-type: multipart/form-data" \
    -H "authorization: bearer ${AT}" \
    -XPOST \
    --key ~/.esvp/LightshipSecurity_Alex_Thurston_ESVDemo.key.pem \
    --cert ~/.esvp/LightshipSecurity_Alex_Thurston_ESVDemo.cer \
    https://demo.esvts.nist.gov:7443/esv/v1/entropyAssessments/10025/dataFiles/10070
```

What I get as a response is:

```json
[
  {
    "esvVersion": "1.0"
  },
  {
    "uploadType": "UploadDataFile",
    "status": "Upload failed for eaID: 10025, dfID: 10070. File not found"
  }
]
```

**Comment by celic** [comment]
Hm, I'm not an expert with cURL. We use Postman for a lot of our internal testing. It however can convert the API requests into cURL. Here is a request we have for uploading a file.
![image](https://user-images.githubusercontent.com/2558865/107799786-e81a6f80-6d2b-11eb-85a5-33b740fb4e2c.png)

In cURL this becomes

```
curl --location --request POST 'https://demo.esvts.nist.gov:7443/esv/v1/entropyAssessments/10022/dataFiles/10062' \
--header 'Authorization: Bearer <token>' \
--form 'dataFile=@"/path/to/file/truerand_4bit.bin"'
```

It appears Postman doesn't include the certificate information when generating these requests, so that would be added too. Hopefully this helps.

**Comment by AlexThurston** [comment]
I see the problem.  Documentation here (https://github.com/usnistgov/ESV-Server/blob/f569ae9ab9f2d30adbf615138c3f0a034642fbc6/Entropy%20Source%20Validation%20Protocol.md#data-files)
says the key is `datafile`.

![image](https://user-images.githubusercontent.com/3537360/107814044-4735af80-6d3f-11eb-9e43-469a5b3f43d7.png)

But in your posted screenshot, the key is `dataFile`.  I'm going to guess that's the reason.

**Comment by celic** [comment]
Ah. Let me know if that works for you and I'll update the documentation.

**Comment by AlexThurston** [comment]
Was able to try this out this morning and it looks like that was it.  Just a typo in the documentation.  I'll make a PR to fix it.

**Comment by AlexThurston** [comment]
Nevermind!  You already fixed it.  Closing.
