### ISSUE TITLE
Correct Paths /esv/v1/ vs /esvp/v1/

### ISSUE THREAD

**Issue by mtdownz** [usnistgov/ESV-Server#23]
Can the URL paths be clarified?

The URLs described in the ESV .md file indicate paths all with  .../esv/v1/...  (e.g. /esv/v1/entropyAssessments/...):
https://github.com/usnistgov/ESV-Server/blob/main/Entropy%20Source%20Validation%20Protocol.md

However, the paths within the files being returned by the server show .../esvp/v1/... (e.g. /esvp/v1/entropyAssessments/xxx/dataFiles/xxx)

Can someone please clarify and update the .md file to show what is valid.

Thanks!

**Comment by celic** [comment]
Apparently in some cases in the MD file we use both...

```
[
    {
        "esvVersion": "1.0"
    },
    {
        **"url": "/esvp/v1/entropyAssessments/<eaId>",**
        "createdOn": "2021-01-01T00:00:00.0000000-05:00",
        "expiresOn": "2021-01-31T00:00:00.0000000-05:00",
        "dataFileUrls": [
            {
                **"rawNoiseBits": "/esv/v1/entropyAssessments/<eaId>/dataFiles/<dfId1>"**
            },
            {
                **"restartTestBits": "/esv/v1/entropyAssessments/<eaId>/dataFiles/<dfId2>"**
            },
            {
                **"conditionedBits": "/esv/v1/entropyAssessments/<eaId>/dataFiles/<dfId3>",**
                "sequencePosition": 1
            }
        ],
        "publishable": false,
        "passed": false,
        "isSample": false,
        "accessToken": <jwt-with-claims>
    }
]
```

I'll do a pass through and try to fix all of them. Thanks.

**Comment by celic** [comment]
Updated the spec and the code, this will be fixed in the next release.
