### ISSUE TITLE
Conditioning component parameters not accepted by esv server

### ISSUE THREAD

**Issue by locksmithone** [usnistgov/ESV-Server#25]
I am registering (demo) a conditioning component to the ESV server. It is a SHA2-512 vetted function. The 90B parameters are as follows:

n_in = 4096
h_in = 512
nw = 512
n_out = 512

Thus I have these parameters being submitted to the esvp-server (in json format below; some parameters are omitted):
```
{
    "description": "SHA2-512",
    "minHin": 512,
    "minNin": 4096,
    "nw": 512,
    "nOut": 512,
    "vetted": true,
}
```
The ESV server, however, responds as such to the registration attempt:

```
ACVPProxy (16:57:36) (tid0) Error: Server error response: [
  {
    "esvVersion": "1.0"
  },
  {
    "conditioningComponents": {
      "elementList": [
        {
          "location": "SequencePosition: 1",
          "messageList": [
            "IntegerValueOutOfRangeError: minNin is not between 1 and 512.",
            "DependencyFailed: minHin cannot be validated because its dependent property MinNIn Result Code is Fail."
          ]
        }
      ]
    }
  }
]

```

minNin cannot be greater than minHin for a vetted hash function?

**Comment by celic** [comment]
Ah yeah, this should be checking for a minimum of 512, not a maximum, depending on the conditioning component.

**Comment by celic** [comment]
This will be fixed on the next release.
