### ISSUE TITLE
sdType "EntropyAnalysisReport" or "EntropyAssessmentReport"?

### ISSUE THREAD

**Issue by locksmithone** [usnistgov/ESV-Server#29]
We currently have some ESV submissions that are failing to result into the correct sdType for the EAR documents. Our client is configured to tag the EARs as `sdType = "EntropyAnalysisReport"`. However, it might be the case that this tag was accepted before by the server, but the tag was further modified in a newer version of the server.

In the documentation in this site, we have instances of both tags or types:

In /client/jsons/run.json, line 19, we see:

```
"filePath": "/path/to/report_ear.pdf",
                "comment": "This is a comment about our entropy assessment report",
                "sdType": "EntropyAssessmentReport"
```

In Entropy%20Source%20Validation%20Protocol.md, we have:

> These are done with a POST /esv/v1/supportingDocumentation with the following body

> 
```
Content-Type: multipart/form-data;
Key: isITAR, Value: "on"/"off"
Key: sdComments, Value: <string describing document, optional>
Key: sdFile, Value: <file upload, .doc, .docx, .pdf>
Key: sdType, Value: "EntropyAnalysisReport"/"PublicUseDocument"/"Other"
```
>

May you clarify which sdType name is the correct one.

**Comment by celic** [comment]
This has been fixed. The CMVP will always use "EntropyAssessmentReport". Sorry for any confusion.
