### ISSUE TITLE
The spec does not appear to be updated for version 1.3.1

### ISSUE THREAD

**Issue by mmccarl** [usnistgov/ESV-Server#31]
the release notes indicate that alphabetsize has been removed from the registration and all conditioning components require h_out, but the spec doesn't agree with these notes.  Are any other changes required?

**Comment by celic** [comment]
Those should be the only changes to the spec. I'll get this updated.

**Comment by celic** [comment]
That is a good question. I think an auditor (probably me) would need to acknowledge this. I do not want to up the version over minor elements. It would be best practice to know what version of the server was used on a particular request, but that could also be figured out afterwards based on the releases tracked by this repository. 

I think the repeatability of submissions to ESVTS is not a high priority within the scope. Repeatability of statistical testing is significantly more important. If we do revise this scope, I think this would be important to reflect in the requirements. Thank you for pointing this out.
