### ISSUE TITLE
Server refuses registration of DRBG as vetted conditioning component (IG D.K)

### ISSUE THREAD

**Issue by locksmithone** [usnistgov/ESV-Server#33]
While attempting to register an ESV having a 90A DRBG as vetted conditioning component, the registration is rejected by the ESV server, stating that the DRBG (a ctrDRBG in this case) does not exist in the vetted conditioning table. We verified the same error with other DRBGs (hashDRBG, hmacDRBG).

I suspect the server still cannot recognize the DRBGs as vetted components, as allowed in IG D.K.

**Comment by celic** [comment]
Yes we're working on it for v1.4 Release in the next month or so.

**Comment by celic** [comment]
This is fixed for RELEASE/v1.4 coming out later today or tomorrow.
