### ISSUE TITLE
ESV results for conditioning component returns null value for SHA256 hash

### ISSUE THREAD

**Issue by amasino** [usnistgov/ESV-Server#34]
When retrieving the results from the ESV server, the conditioning component provides the sha256 json field with null values.

[conditioning1-ea-result.txt](https://github.com/usnistgov/ESV-Server/files/11250539/conditioning1-ea-result.txt)

**Comment by celic** [comment]
Thanks for the heads up. We'll address this in the upcoming v1.4 release.

**Comment by celic** [comment]
This is fixed for RELEASE/v1.4 coming out later today or tomorrow.
