### ISSUE TITLE
ITAR was deprecated 2023/03/08, but server still expects it

### ISSUE THREAD

**Issue by locksmithone** [usnistgov/ESV-Server#35]
While submitting a new ESV to the demo server, the ITAR and alphabetSize fields were removed from registration files. But while attempting to register, here is a portion of the error returned by the server:

> ACVPProxy (09:37:56) (tid1897) Error: ESVP server returned error Error: isITAR is null. during uploading of file
> ACVPProxy (09:37:56) (tid1897) Error: Cannot process server request -22:
>  [
>   {
>     "esvVersion": "1.0"
>   },
>   {
>     "uploadType": "UploadSupportingDocumentation",
>     "status": "Error: isITAR is null."
>   }
> ]

It would seem the ESV server still expects ITAR values.

**Comment by celic** [comment]
Thanks for the heads up. We'll address this in the upcoming v1.4 release.

**Comment by celic** [comment]
I double checked this with the current release going out today or tomorrow RELEASE/v1.4. The `isITAR` property is not expected for the registration, but is expected for the supporting documentation uploads. This is accurate in the protocol specification.
