### ISSUE TITLE
ESV Demo Server Rejects DRBG Vetted Conditioning Component

### ISSUE THREAD

**Issue by afazio2** [usnistgov/ESV-Server#37]
My noise source has an AES-256 CTR DRBG and SHA2-512 HMAC-DRBG conditioning components.
Following IG D.K bullet (7) Note 1. "A CAVP-validated SP 800-90A DRBG may be considered a vetted conditioning component."

I register:

{
	"_description": "Kernel_HMAC-SHA-512_DRBG",
	"description": "SHA2-512 HMAC-DRBG",
	"minHin": 256.0,
	"minNin": 256,
	"nw": 256,
	"nOut": 256,
	"hOut": 256.0,
	"vetted": true,
	"bijective": false,
	"acvtsCertificate": "A4025"
}

and

{
	"_description": "OpenSSL_CTR_DRBG_AES-256",
	"description": "AES-256 CTR-DRBG",
	"minHin": 256.0,
	"minNin": 256,
	"nw": 256,
	"nOut": 256,
	"hOut": 256.0,
	"vetted": true,
	"bijective": false,
	"acvtsCertificate": "A4053"
}

The server returns the following error:

{
  "esvVersion": "1.0"
},
{
  "conditioningComponents": {
    "elementList": [
      {
        "location": "SequencePosition: 2",
        "messageList": [
          "DescriptionError: description: SHA2-512 HMAC-DRBG does not exist in the VettedConditioningComponentAttributes table.",
          "DependencyFailed: nw cannot be validated because its dependent property Description Result Code is Fail.",
          "DependencyFailed: nOut cannot be validated because its dependent property Description Result Code is Fail.",
          "DependencyFailed: hOut cannot be validated because its dependent property NOut Result Code is Fail."
        ]
      },
      {
        "location": "SequencePosition: 3",
        "messageList": [
          "DescriptionError: description: AES-256 CTR-DRBG does not exist in the VettedConditioningComponentAttributes table.",
          "DependencyFailed: nw cannot be validated because its dependent property Description Result Code is Fail.",
          "DependencyFailed: nOut cannot be validated because its dependent property Description Result Code is Fail.",
          "DependencyFailed: hOut cannot be validated because its dependent property NOut Result Code is Fail."
        ]
      }
    ]
  }
}

**Comment by celic** [comment]
The names should be `"AES-256-CTR-DRBG"` and `"SHA2-512-HMAC-DRBG"`.

**Comment by amasino** [comment]
Hi Chris, 

I believe that the "Entropy Source Validation Protocol.md" file should be updated, it includes underscores instead of hyphens.

Is the new set of algorithms allowed for conditioning component deployed in production?

**Comment by celic** [comment]
I updated the protocol document. This is not yet on Prod, we typically keep this up on Demo for a week to ensure it's stable before moving it over to Prod. If you've tested on Demo and are satisfied (we've done our own testing), I'm OK moving this over to Prod sooner.

**Comment by celic** [comment]
We have since updated the documentation to ensure it is correct and deployed this to Prod.
