### ISSUE TITLE
Production server provides incorrect results in json file for restart statistical tests

### ISSUE THREAD

**Issue by amasino** [usnistgov/ESV-Server#38]
The results provided in the production server differ from the ones obtained executing the same ESV submission in the demo server. Specifically, the statistical results for restart has several issues:

- "Estimate entropy with Most Common Value" entry duplicated
- No overall results.
- Several tests provide the same results as the "Estimate entropy with t-Tuple Test" for either h_c, h_r, or both
   - "Estimate entropy with LRS Test"
   - "Estimate entropy with Multi Most Common in Window Test"
   - "Estimate entropy with Lag Prediction Test"
   - "Estimate entropy with Multi Markov Model with Counting Test (MultiMMC)"
   - "Estimate entropy with LZ78Y Test"

Results for one shot raw data are correct.

As the statistical results are not accurate in the production server, it is not clear for the lab whether to proceed or not with the certification of the ESV submission already registered.  

Json files provided (renamed with txt extension as json files are not allowed)

[restart-entropy-rate -prod-testid-0704.txt](https://github.com/usnistgov/ESV-Server/files/12229632/restart-entropy-rate.-prod-testid-0704.txt)
[restart-entropy-rate-demo-testid-2913.txt](https://github.com/usnistgov/ESV-Server/files/12229633/restart-entropy-rate-demo-testid-2913.txt)

**Comment by celic** [comment]
Thanks, this tells me we may have missed updating our Docker containers with the new C++ tool build when we did our Prod deployment. Let me check on this.

**Comment by celic** [comment]
My guess was correct. There was a hidden issue grabbing the "latest" for the Prod docker containers. This is fixed. Thank you for letting us know.
