### ISSUE TITLE
Requirement of conditioned bits

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ESV-Server#4]
In a previous discussion, I was under the impression that uploading of conditioned bits for a conditioning component is only required if the conditioning component is not a vetted algorithm.

Now, I have a vetted algorihtm (SHA2-256 in my case) and the server requests the conditioned data:

```
"RequiredPropertyError: conditionedBitsSHA256 was not found in the JSON payload."
```

Could you please help me understand when this data is required?

**Comment by celic** [comment]
Ah for a vetted conditioning component, no file upload is required, so it doesn't make sense to expect a hash of the file you aren't uploading. I'll get this fixed.
