### ISSUE TITLE
File Size Upload Restricted to 1MB Instead of 1GB

### ISSUE THREAD

**Issue by hbarton-atsec** [usnistgov/ESV-Server#44]
The ESV server seems to be limited to 1MB file size uploads instead of 1GB file size uploads. Chris Celi had mentioned previously that the server should accept 1GB file size uploads.

**Comment by celic** [comment]
Each individual sample file is limited to 1MB. The overall submission, all sample files and documentation (if you are using the WebClient), may total under 500MB, down from 1GB because we didn't see a need for submissions that large.

**Comment by hbarton-atsec** [comment]
Ok thanks for the clarification.
