### ISSUE TITLE
[Clarification Required]: Do we need accredited CST laboratories and 17ACVT laboratories to complete Entropy Source Validation certification

### ISSUE THREAD

**Issue by ranjankumar23** [usnistgov/ESV-Server#51]
I have been going through all NIST archive and latest documents.
As per latest information entropy source validation can be done by ESV automated server and get final certificate.

Or CST Lab is must to engage with for final certificate?

Is my understanding correct?

**Comment by celic** [comment]
You need to go through an accredited 17EV lab (usually your CST lab) to submit for a validation certificate that appears on CSRC. 

The Demo server is just for testing. It essentially just runs the C++ Entropy Assessment Library available here: https://github.com/usnistgov/SP800-90B_EntropyAssessment.

**Comment by ranjankumar23** [comment]
> You need to go through an accredited 17ESV lab (usually your CST lab) to submit for a validation certificate that appears on CSRC.
> 
> The Demo server is just for testing. It essentially just runs the C++ Entropy Assessment Library available here: https://github.com/usnistgov/SP800-90B_EntropyAssessment.

Thank you Chris. It is clear now.
