### ISSUE TITLE
ESV does not accept large document files

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ESV-Server#7]
I try to upload the PDF from https://www.chronox.de/jent/doc/CPU-Jitter-NPTRNG.pdf and it fails with:

```
HTTP/1.1 413 Request Entity Too Large
```

**Comment by celic** [comment]
How large is the file? I see it at 13.2MB. That should be a reasonable size. I'll double check the maximum allowed. This is defined by the IIS server and the code, so we need to make sure this matches in all locations.
