### ISSUE TITLE
ESV exception after uploading all data

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ESV-Server#8]
After uploading all data (raw noise, restart, documentation), I get:

```
[
  {
    "esvVersion": "1.0"
  },
  {
    "uploadType": "UploadSupportingDocumentation",
    "status": "Exception ocurred: Invalid Model State. The file type isn\u0027t permitted or the file\u0027s signature doesn\u0027t match the file\u0027s extension."
  }
]
```

Upload performed for /esvp/v1/entropyAssessments/10103

**Comment by smuellerDD** [comment]
the issue is caused by an unexpected file type - but should the exception be called "Invalid Model State"?

**Comment by smuellerDD** [comment]
Am Dienstag, dem 09.03.2021 um 09:28 -0800 schrieb Chris Celi:
> The error should be clearer. We only accept doc, docx, pdf here. If you have
> a justification for other files, we can discuss them. 
> 
I think I would allow plain ASCII and maybe a few graphics formats (e.g. PNG,
JPG, SVG for starters). But beyond that I am not sure you should allow more
for now.

But my note was more about the error message which seemed to indicate that the
server had an error that I triggered by using an unsupported file format. If
you think that the error message is as you like it, please close that report
at your discretion.

Thanks
Stephan

**Comment by celic** [comment]
The error should be clearer that we are intentionally rejecting other file
formats. The reason we decided against pure image formats was that they
should be accompanied by some justification. Which I suppose could be in a
separate document.

**Comment by smuellerDD** [comment]
Am Dienstag, dem 09.03.2021 um 11:36 -0800 schrieb Chris Celi:
> The error should be clearer that we are intentionally rejecting other file
> formats. The reason we decided against pure image formats was that they
> should be accompanied by some justification. Which I suppose could be in a
> separate document.

Indeed. At least we sometimes get pure graphics files that are accompanied by
description documents.

In any case, since a human needs to vet these documents, I personally do not
think that there is any harm allowing a graphics format. That human can easily
reject anything that is not intelligible.

**Comment by celic** [comment]
Sort of. In the end we are building a package to send to the reviewer. It's
a slightly different process here than ACVP. The documents aren't viewed
until the actual review is occurring.
