### ISSUE TITLE
ESV: Next step after data uploading?

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ESV-Server#9]
After finally getting all data uploaded (raw, restart, documentation), I get a verdict of success from the server. Yet, after sending the documentation, I also get a new access token.

What shall happen now?

**Comment by celic** [comment]
Documentation needs an access token because we've broken out the Certify process from the Entropy Assessment (Test Session). Certify is a separate end-point that accepts the eaIds, sdIds, and tokens for each to prove ownership.

**Comment by smuellerDD** [comment]
> Am 09.03.2021 um 20:39 schrieb Chris Celi <notifications@github.com>:
> 
> ﻿
> That's it. The documentation was uploaded and is waiting to be used in a
> certify when you are ready.

Maybe I miss a point here: what is the „certify“ operation? A PUT ?

Thanks
Stephan
> 
>

**Comment by celic** [comment]
Ah. Yeah the documentation doesn't have it yet because that endpoint is still in progress. The Certify will be a separate POST on a new endpoint. This is different than ACVP does it, and allows us to include multiple EAs in one request.

**Comment by smuellerDD** [comment]
> Am 09.03.2021 um 20:58 schrieb Chris Celi <notifications@github.com>:
> 
> ﻿
> Ah. Yeah the documentation doesn't have it yet because that endpoint is still in progress. The Certify will be a separate POST on a new endpoint. This is different than ACVP does it, and allows us to include multiple EAs in one request.
> 

Ok, then I will wait until you are ready. 

But what about providing the URI in the answer from the server just like the URLs provided in various ACVP responses?

Ciao
Stephan

**Comment by celic** [comment]
You mean the URI to the document that was just uploaded? We didn't intend for them to be retrievable by users. We should return the ID though (which was all the information the URIs were meant to provide). This is coming soon.

**Comment by smuellerDD** [comment]
> You mean the URI to the document that was just uploaded? We didn't intend for them to be retrievable by users. We should return the ID though (which was all the information the URIs were meant to provide). This is coming soon.
> 

I am referring to the URI for the next step, the certify operation. But that is only an idea without knowing how that certify is supposed to work.

Ciao
Stephan

**Comment by celic** [comment]
Yes you'll need the ID (which would be in the URI) for the Certify. Sorry, I was a bit confused. This is already done in our development branch of the Certify step, so I was getting a bit mixed up on what is on Demo versus our internal environment here.
